# Generated by Django 4.2.30 on 2026-07-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cinema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.TextField()),
                ("telephone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("genre", models.CharField(max_length=50)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=3)),
                ("affiche", models.ImageField(upload_to="evenements/")),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                ("duree", models.IntegerField()),
                ("genre", models.CharField(max_length=50)),
                ("date_sortie", models.DateField()),
                ("realisateur", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=6)),
                ("affiche", models.ImageField(upload_to="films/")),
            ],
        ),
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("capacite", models.IntegerField()),
                ("disponible", models.BooleanField(default=True)),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seance_app.cinema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programme", models.CharField(blank=True, max_length=15, null=True)),
                ("place_dispo", models.IntegerField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateTimeField()),
                (
                    "horaire",
                    models.CharField(
                        choices=[
                            ("10h", "10h"),
                            ("14h", "14h"),
                            ("17h", "17h"),
                            ("21h", "21h"),
                        ],
                        max_length=10,
                    ),
                ),
                ("prix", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "evenement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seance_app.evenement",
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seance_app.film",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seance_app.salle",
                    ),
                ),
            ],
        ),
    ]
