# Generated by Django 4.2.30 on 2026-07-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seance_app.evenement'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seance_app.film'),
        ),
    ]
