# Generated by Django 4.2.30 on 2026-07-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seance_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seance",
            name="prix",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
