# Generated by Django 4.2.30 on 2026-07-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seance_app", "0002_alter_seance_prix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evenement",
            name="prix",
        ),
        migrations.RemoveField(
            model_name="film",
            name="prix",
        ),
    ]
