# Generated by Django 4.2.30 on 2026-10-08 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import account_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("account_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birthday",
                    models.DateTimeField(default=account_app.models.random_birthday),
                ),
                (
                    "bankName",
                    models.CharField(
                        default=account_app.models.random_bank, max_length=50
                    ),
                ),
                (
                    "accountNb",
                    models.CharField(
                        default=account_app.models.random_account_number, max_length=50
                    ),
                ),
                (
                    "accountBalance",
                    models.FloatField(default=account_app.models.random_balance),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
